### ISSUE TITLE
Pretty print in dev?

### ISSUE THREAD

**Issue by jamesdixon** [mcollina/hapi-pino#4]
Hi! I was looking for something a bit more lightweight than good and stumbled across pino. I saw that there is a command line utility to pretty print a log file -- is it possible to pretty print while in development only? I obviously use the console and the JSON is a bit difficult to read -- would be great to be able to view logging in 'pretty mode' while developing.

Cheers.

**Comment by mcollina** [comment]
you just have to do:

```js
npm i pino -g
```

```
node yourserver.js || pino
```

Or were you thinking doing something different? Maybe turned on/off via a flag?

**Comment by jamesdixon** [comment]
Hmm, I can't seem to get that to work.

```
> node --use-strict start.js || pino

{"pid":20725,"hostname":"baldr.local","level":30,"time":1461225638969,"tags":["info","hapi-ioredis"],"data":"connected to redis","v":1}
{"pid":20725,"hostname":"baldr.local","level":30,"msg":"server started","time":1461225639756,"created":1461225637971,"started":1461225639753,"host":"baldr.local","port":3001,"protocol":"https","id":"baldr.local:20725:ina00m6r","uri":"https://baldr.local:3001","address":"0.0.0.0","v":1}
```

I was thinking more along the lines of a flag, so I could just set the flag based on my environment.

**Comment by jamesdixon** [comment]
That said, if I can get the solution you recommended to work, that's all good too 👍

**Comment by jamesdixon** [comment]
Ah, only one pipe needed!

**Comment by jamesdixon** [comment]
However, just tried this same method with tests and the pretty output doesn't seem to work. Have you tried that when using Hapi/Lab?

**Comment by mcollina** [comment]
oh, that's an interesting use case. No, I never did as I usually turn off all the logging in test (too noisy for me). However I'm open to support it somehow.

So, I think we should export the pretty-printer as a transform stream from pino.
something like:

```js
let pretty = pino.pretty()
pretty.pipe(process.stdout)
pino(pretty)
```

Or maybe something in pino:

```js
pino({ devmode: true })
```

which automatically pretty prints (based on the above anyway).

@davidmarkclements what do you think?

**Comment by davidmarkclements** [comment]
If we do a `{devmode: true}` you may as well go the whole hog and make it a flag. 

I think a flag is more Hapi style (probably why @jamesdixon was originally looking for a flag)

However, exporting the pretty printer is more pino style (this is same old framework vs modularity contention). 

This is a hapi plugin, I think it should conform to the common paradigms users of Hapi are familiar with, so I think we should provide a flag. 

If we call it `--dev-pretty` or something, that'll hopefully discourage use in production. 

Another option is to pretty print if `process.env.NODE_ENV !== 'production'` or if there's some other idiomatic Hapi way to check for dev vs prod environment

**Comment by mcollina** [comment]
@geek is there a way we can detect if we inside a Lab test? Or Hapi is being tested? Or Hapi is in production?

I think we can support a combination of:

* `PRETTY_PINO=true`
* `pino({ devPretty: true })` - support `devPretty` in pino (I'm 👎  on this)
* `--dev-pretty` from the CLI options - it might not be a good idea, because other programs might not like if we are adding stuff to the arguments 
* `server.register({ register: Pino.register, options: { devpretty: true }}, (err) => {})`

The first step is to export the pretty printer, which we all agree on, right?

This will enable:

```js
const pretty = Pino.pretty()
pretty.pipe(stdout)
server.register({
  register: Pino.register,
  options: { stream: pretty }
}, (err) => {})
```

**Comment by davidmarkclements** [comment]
Good point on flags. 

I think the environment var is better, but call it `PRETTY_DEV_LOGS` and it's ignored if NODE_ENV is production


In terms of export, what if we:

`pino.stream.pipe(require('pino-transform')).pipe(process.stdout)`

**Comment by mcollina** [comment]
```js
pino.stream.pipe(require('pino-transform')).pipe(process.stdout)
```

Won't work. the stream is passed in through. Also, I do not want pino to depend on pino-transport, so I ill all put it inside pino :).

So I think we should:

1. expose the transform from pino `bin.js`.
2. add a `devPretty` flag in pino to pretty print, which is automatically disabled if `NODE_ENV=production`

This will make this behavior non-specific to hapi-pino, because I think it's more general.

@geek please read this through if there is a better way for doing all of this in Hapi-land.

**Comment by jamesdixon** [comment]
I personally like the simple flag as an option when registering the Hapi plugin. Then you can do something like to determine whether to run the pretty printer in a specific environment:

```javascript
server.register({
    register: require('hapi-pino'),
    options: {
        prettyPrint: process.env.NODE_ENV !== 'production'
    }
}
...
```

It also doesn't make any assumptions about the environment (ex: some people may use 'prod' rather than 'production').

Thoughts?

**Comment by mcollina** [comment]
Pretty print is released in v1.1.0. Let me know what you think @jamesdixon!

**Comment by jamesdixon** [comment]
Awesome! I'll give it a shot in a few. Thanks :)

**Comment by jamesdixon** [comment]
Works beautifully 👍
